/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGuessRouteImport } from './routes/api/guess'
import { Route as ApiDailyRouteImport } from './routes/api/daily'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuessRoute = ApiGuessRouteImport.update({
  id: '/api/guess',
  path: '/api/guess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyRoute = ApiDailyRouteImport.update({
  id: '/api/daily',
  path: '/api/daily',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/daily': typeof ApiDailyRoute
  '/api/guess': typeof ApiGuessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/daily': typeof ApiDailyRoute
  '/api/guess': typeof ApiGuessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/daily': typeof ApiDailyRoute
  '/api/guess': typeof ApiGuessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/daily' | '/api/guess'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/daily' | '/api/guess'
  id: '__root__' | '/' | '/api/daily' | '/api/guess'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDailyRoute: typeof ApiDailyRoute
  ApiGuessRoute: typeof ApiGuessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guess': {
      id: '/api/guess'
      path: '/api/guess'
      fullPath: '/api/guess'
      preLoaderRoute: typeof ApiGuessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily': {
      id: '/api/daily'
      path: '/api/daily'
      fullPath: '/api/daily'
      preLoaderRoute: typeof ApiDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDailyRoute: ApiDailyRoute,
  ApiGuessRoute: ApiGuessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
